In [5]:
import numpy as np

In [7]:
mylist = [1, 2, 4]

In [10]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [29]:
np.eye(1000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [53]:
np.random.rand(4, 2)

array([[0.65028914, 0.68822225],
       [0.72747835, 0.70098595],
       [0.80121573, 0.89662509],
       [0.75745133, 0.78350521]])