In [5]:
import numpy as np

In [7]:
mylist = [1, 2, 4]

In [10]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [29]:
np.eye(1000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [55]:
np.random.rand(4, 2)

array([[0.09314807, 0.96809315],
       [0.49741591, 0.6247405 ],
       [0.38063839, 0.26982534],
       [0.17905531, 0.50791982]])

In [91]:
np.random.randint(0, 20, (4, 8))

array([[17, 16,  0, 19,  2,  3, 18,  9],
       [17,  5, 14, 13, 13, 15, 14,  9],
       [ 2,  8,  0, 11, 16, 16,  9,  3],
       [ 2, 18, 10, 18, 11, 17, 18,  5]])

In [95]:
np.random.seed(90)

In [99]:
"Numpy - индексация и выборки"

'Numpy - индексация и выборки'

In [103]:
arr = np.arange(1, 12)

In [105]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
arr[0:5] = 100

In [108]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11])