In [6]:
import numpy as np

In [7]:
mylist = [1, 2, 4]

In [8]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [9]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [12]:
np.eye(1000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [13]:
np.random.rand(4, 2)

array([[0.49239274, 0.38648084],
       [0.44477901, 0.14596836],
       [0.42570902, 0.85803526],
       [0.0685044 , 0.09317611]])

In [14]:
np.random.randint(0, 20, (4, 8))

array([[16, 18,  3,  5, 10, 19, 18, 15],
       [ 5,  4,  9, 14,  4,  4,  9,  5],
       [ 5,  0, 16, 13,  8, 14,  2, 18],
       [ 3,  6, 12,  2,  6,  2, 18,  1]])

In [15]:
np.random.seed(90)

In [16]:
"Numpy - индексация и выборки"

'Numpy - индексация и выборки'

In [17]:
arr = np.arange(1, 12)

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
arr[0:5] = 100

In [20]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11])

In [21]:
arr_2d = np.array([[2, 5], [2, 5]])

In [22]:
arr_c = arr_2d.copy()

In [23]:
arr_c[0] = 100

In [24]:
arr_c

array([[100, 100],
       [  2,   5]])

In [25]:
arr_2d

array([[2, 5],
       [2, 5]])

In [26]:
arr_2d > 2

array([[False,  True],
       [False,  True]])

In [27]:
"Операции в Numpy"

'Операции в Numpy'

In [28]:
arr_2d.sum()

14

In [30]:
arr_2d.sum(axis=0)

array([ 4, 10])

In [35]:
new_arr = np.arange(10, 51, 2)

In [36]:
new_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [37]:
mat = np.arange(1, 26).reshape(5, 5)

In [38]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
mat(2:)

SyntaxError: invalid syntax (133912210.py, line 1)