In [5]:
import numpy as np

In [7]:
mylist = [1, 2, 4]

In [10]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0, 10, 11)

array([ 0.,  5., 10.])